[tool.poetry]
name = "i2cftdi"
version = "0.1.0"
description = ""
authors = ["Ernie <ernie@earthtoernie.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
